import Head from "next/head";
import Link from "next/link";


export default function Home() {
  const slug = "ea-sit-ea-explicabo-hic-quidem-in"; // Hardcoded slug

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Next.js!</h1>
        <Link href={`/${slug}`}>
          <h2>Go to Post</h2>
        </Link>
      </main>
    </>
  );
}
